namespace Webrtc{
	[default_interface]
	runtimeclass WebrtcManager
	{
		WebrtcManager();
		WebrtcManager(String outputDeviceId, String inputDeviceId);
		void Create();
		void Destroy();

		Windows.Foundation.IAsyncAction ConnectAsync(String ip, String port, UInt32 ssrc);
		void SendSelectProtocol(UInt32 ssrc);

		void SetKey(UInt8[] key);
		void SetSpeaking(UInt32 ssrc, Int32 speaking);

		void SetPlaybackDevice(String deviceId);
		void SetRecordingDevice(String deviceId);

		event Windows.Foundation.TypedEventHandler<String, UInt16> IpAndPortObtained;
		event Windows.Foundation.EventHandler<Windows.Foundation.Collections.IVector<Single> > AudioInData;
		event Windows.Foundation.EventHandler<Windows.Foundation.Collections.IVector<Single> > AudioOutData;
		event Windows.Foundation.EventHandler<Boolean> Speaking;
	}
}