namespace Webrtc{

	delegate void IpAndPortObtainedDelegate(String ip, UInt16 port);
	delegate void AudioInDataDelegate(Windows.Foundation.Collections.IVector<Single> data);
	delegate void AudioOutDataDelegate(Windows.Foundation.Collections.IVector<Single> data);
	delegate void SpeakingDelegate(Boolean speaking);
		
	[default_interface]
	runtimeclass WebrtcManager
	{
		WebrtcManager();
		WebrtcManager(String outputDeviceId, String inputDeviceId);
		void Create();
		void Destroy();

		void Connect(String ip, String port, UInt32 ssrc);
		void SendSelectProtocol(UInt32 ssrc);

		void SetKey(UInt8[] key);
		void SetSpeaking(UInt32 ssrc, Int32 speaking);

		void SetPlaybackDevice(String deviceId);
		void SetRecordingDevice(String deviceId);

		void SetVideoStream(UInt64 userId, UInt32 ssrc);

		void GenerateSample(Windows.Media.Core.MediaStreamSourceSampleRequest request);

		IpAndPortObtainedDelegate IpAndPortObtained;
		AudioInDataDelegate AudioInData;
		AudioOutDataDelegate AudioOutData;
		SpeakingDelegate Speaking;
	}
}