// Adam Dernis © 2022

namespace Discord.API.Models.Enums.Guilds
{
    public enum GuildFeature
    {
        None = 0,
        AnimatedBanner = 1 << 0,
        AnimatedIcon = 1 << 1,
        Banner = 1 << 2,
        ChannelBanner = 1 << 3,
        Commerce = 1 << 4,
        Community = 1 << 5,
        Discoverable = 1 << 6,
        DiscoverableDisabled = 1 << 7,
        EnabledDiscoverableBefore = 1 << 8,
        Featureable = 1 << 9,
        ForceRelay = 1 << 10,
        HasDirectoryEntry = 1 << 11,
        Hub = 1 << 12,
        InternalEmployeeOnly = 1 << 13,
        InviteSplash = 1 << 14,
        LinkedToHub = 1 << 15,
        MemberProfiles = 1 << 16,
        MemberVerificationGateEnabled = 1 << 17,
        MonetizationEnabled = 1 << 18,
        MoreEmoji = 1 << 19,
        MoreStickers = 1 << 20,
        News = 1 << 21,
        NewThreadPermissions = 1 << 22,
        Partnered = 1 << 23,
        PremiumTier3Override = 1 << 24,
        PreviewEnabled = 1 << 25,
        PrivateThreads = 1 << 26,
        RelayEnabled = 1 << 27,
        RoleIcons = 1 << 28,
        RoleSubscriptionsAvailableForPurchase = 1 << 29,
        RoleSubscriptionsEnabled = 1 << 30,
        SevenDayThreadArchive = 1 << 31,
        TextInVoiceEnabled = 1 << 32,
        ThreadsEnabled = 1 << 33,
        ThreadsEnabledTesting = 1 << 34,
        ThreadsDefaultAutoArchiveDuration = 1 << 35,
        ThreeDayThreadArchive = 1 << 36,
        TicketedEventsEnabled = 1 << 37,
        VanityUrl = 1 << 38,
        Verified = 1 << 39,
        VIPRegions = 1 << 40,
        WelcomeScreenEnabled = 1 << 41,
    }
}
